name: RSS
author: thinkphp
current: v1.0
category: utilities
tags: [rss,xml,syndication,feed,aggregators]
docs: https://github.com/thinkphp/MooRSS/blob/master/Docs/RSS.md
demo: http://thinkphp.ro/apps/js-hacks/MooRSS/v1/rss.html 